name: "Github action playground"

on:
  push:
  workflow_dispatch:

jobs:
  print-something:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ fromJSON('["ubuntu-latest", "self-hosted"]')}}

